import "../../Fastfile"

default_platform(:mac)

platform :mac do
  desc "Build an unsigned macOS app bundle"
  lane :build_unsigned do
    fetch_dependencies
    sh_on_root(command: <<~CMD)
      export CODE_SIGNING_ALLOWED=NO
      export CODE_SIGNING_REQUIRED=NO
      flutter build macos --release
    CMD
  end
end
