import "../../Fastfile"

default_platform(:ios)

platform :ios do
  desc "Build an unsigned iOS app bundle for local packaging/signing"
  lane :build_unsigned do
    fetch_dependencies
    sh_on_root(command: <<~CMD)
      export CODE_SIGNING_ALLOWED=NO
      export CODE_SIGNING_REQUIRED=NO
      flutter build ios --release --no-codesign
    CMD
  end
end
